name: Build

on:
  # Run on all PRs
  pull_request:
  # Run when a PR is merged into main
  push:
    branches:
      - main
  # Run when a release is published
  release:
    types:
      - published

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bundle the library
        uses: hasnep/publish-roc-library@main
