name: Generate docs

on:
  # Run when a release is published
  release:
    types:
      - published

jobs:
  generate-docs:
    name: Bundle
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Install Roc
        uses: hasnep/setup-roc@main
        with:
          roc-version: nightly
      - name: Generate docs
        run: roc docs Json/main.roc
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: generated-docs
